---
title: "FlexDashboard"
author: "Santosh Agastyaraju"
output:  
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(ggplot2)
library(shiny)

setwd="F:\\GLIMS-PGPBDA\\Assignments\\SVAP-Assignment\\Assignment-3\\"
rawdata = read.csv("Production-Department_of_Agriculture_and_Cooperation_1.csv")
dataset = rawdata

```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
sliderInput('TotalStats', 'Total Stats', min=1, max=nrow(dataset),
            value=min(10, nrow(dataset)), step=5, round=0)

checkboxInput('State', 'State', value = TRUE)
selectInput('x', 'X', names(dataset))
selectInput('y', 'Y', names(dataset), names(dataset)[[13]])
```

Outputs
-----------------------------------------------------------------------

### AgricultureData

```{r}
dataset <- reactive({
  rawdata[sample(nrow(rawdata), input$TotalStats),]
})

renderPlot({
  p <- ggplot(dataset(), aes_string(x=input$x, y=input$y, size=10)) + geom_point()
  print(p)
})
```